# Generated by Django 4.2.2 on 2023-10-17 12:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0008_dish_quantity'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feedback',
            unique_together={('user', 'rating', 'review'), ('user',), ('rating',), ('user', 'rating'), ('review',), ('rating', 'user'), ('user', 'review'), ('review', 'user'), ('review', 'rating'), ('rating', 'review')},
        ),
    ]
