# Generated by Django 4.2.2 on 2023-10-17 12:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0009_alter_feedback_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dish_feedback',
            unique_together={('review', 'user'), ('user', 'rating'), ('user', 'rating', 'review'), ('rating',), ('review',), ('rating', 'review'), ('user', 'review'), ('user',), ('rating', 'user'), ('review', 'rating')},
        ),
    ]
