# Generated by Django 4.2.2 on 2023-10-18 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_alter_dish_feedback_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='avg_rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
    ]
