# Generated by Django 4.2.2 on 2023-10-18 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0011_restaurants_avg_rating'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dishes',
            unique_together={('restaurant', 'name')},
        ),
    ]
