# Generated by Django 4.2.2 on 2023-10-22 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0013_alter_feedback_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='closing_time',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='opening_time',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
