# Generated by Django 4.2.2 on 2023-10-24 05:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0016_user_address'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user_address',
            unique_together={('user', 'address_type')},
        ),
        migrations.AddConstraint(
            model_name='user_address',
            constraint=models.UniqueConstraint(condition=models.Q(('address_type', 'home')), fields=('user', 'address_type'), name='unique_home_address'),
        ),
    ]
