# Generated by Django 4.2.2 on 2023-10-24 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0018_offers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='restaurant',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurants'),
        ),
        migrations.CreateModel(
            name='Dine_in',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakfast', models.IntegerField(default=10)),
                ('lunch', models.IntegerField(default=10)),
                ('dinner', models.IntegerField(default=10)),
                ('date', models.DateField()),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurants')),
            ],
            options={
                'unique_together': {('restaurant', 'date')},
            },
        ),
    ]
