# Generated by Django 4.2.2 on 2023-10-24 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0019_alter_offers_restaurant_dine_in'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dine_in',
            new_name='Tables_Available',
        ),
    ]
