# Generated by Django 4.2.2 on 2023-10-24 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0021_user_dinein'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='value',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
