# Generated by Django 4.2.2 on 2023-10-25 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0023_cart_alter_dish_quantity_unique_together_cartitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='applied_coupon',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='delivery_address',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='dish',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
