# Generated by Django 4.2.2 on 2023-10-25 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0028_cartitembranch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='user',
        ),
    ]
