# Generated by Django 4.2.2 on 2023-10-26 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0029_remove_checkout_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
