# Generated by Django 4.2.2 on 2023-10-26 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0030_restaurantfeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='features',
            field=models.ManyToManyField(blank=True, to='restaurant.restaurantfeature'),
        ),
    ]
