# Generated by Django 4.2.2 on 2023-10-26 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0031_restaurants_features'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart_Items',
        ),
    ]
