# Generated by Django 4.2.2 on 2023-10-26 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0032_delete_cart_items'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cartitembranch',
            new_name='Cart_Items',
        ),
    ]
