# Generated by Django 4.2.2 on 2023-10-26 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0034_orderhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderhistory',
            name='order_id',
        ),
    ]
