# Generated by Django 4.2.2 on 2023-10-30 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0036_reward'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dish_Feedback',
        ),
    ]
