# Generated by Django 4.2.2 on 2023-10-30 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0038_dishes_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish_quantity',
            name='avg_rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
    ]
